// Auto-generated by LibreLane
module layer_output(
`ifdef USE_POWER_PINS
  inout vdd,
  inout vss,
  inout VSS,
  inout VDD,
`endif
  input Iext1,
  output vout_1,
  output nvout_1,
  input Iext2,
  output vout_2,
  output nvout_2
);
endmodule
