// Auto-generated by LibreLane
module stdp_4x2(
`ifdef USE_POWER_PINS
  inout avdd,
  inout avss,
`endif
  inout A,
  inout B,
  input nvpre1,
  input vpre1,
  input vpre2,
  input nvpre2,
  input vpre3,
  input nvpre3,
  input vpre4,
  input nvpre4,
  input vpost1,
  input nvpost1,
  input vpost2,
  input nvpost2,
  output ifwd1,
  output ifwd2,
  inout vw11,
  inout vw42
);
endmodule
