// Auto-generated by LibreLane
module layer_input(
`ifdef USE_POWER_PINS
  inout vdd,
  inout vss,
`endif
  input Iext1,
  output vout_1,
  output nvout_1,
  input Iext2,
  output vout_2,
  output nvout_2,
  input Iext3,
  output vout_3,
  output nvout_3,
  output vout_4,
  input Iext4,
  output nvout_4
);
endmodule
