// Auto-generated by LibreLane
module D14_topcell(
`ifdef USE_POWER_PINS
  inout avdd,
  inout avss,
`endif
  input Vin,
  input Vin_neg,
  output vout_1,
  output nvout_1,
  output vout_2,
  output nvout_2,
  output vout_3,
  output nvout_3,
  output vout_4,
  output nvout_4
);
endmodule
